import { ThemeProvider } from "@/providers/theme-provider";
import "./globals.css";
import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import ToastContext from "@/context/toast-context";
import Session from "@/providers/session-proovider";

const font = Josefin_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={font.className}>
        <Session>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ToastContext />
          {children}
        </ThemeProvider>
        </Session>
      </body>
    </html>
  );
}
